### ISSUE TITLE
“whereat” function fails

### ISSUE THREAD

**Issue by adamclaxon** [MoeFwacky/Python-Plex-Controller#3]
When I run `whereat` (or any function that depends on `whereat`, such as `commercialbreak`) I get the following error:

```
Traceback (most recent call last):
  File "/home/pi/hasystem/system.py", line 9328, in <module>
    say = whereat()
  File "/home/pi/hasystem/system.py", line 1215, in whereat
    if int(mediatype.get('time')) != 0:
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by MoeFwacky** [comment]
I am unable to reproduce this error.  I ran `whereat` and got the following output:

```
pi@controller:~ $ whereat
We are at minute 18 out of 27.
```
The only difference I found between the version I'm running and what's on the repo is just an error I fixed on the repo, but forgot to update to locally. I brought my version up to date and still wasn't able to reproduce. Can you explain what you were doing prior to running the `whereat` or `commercialbreak` commands?
